### ISSUE TITLE
Nvidia Docker runtime and Kubernetes Device Plugin

### ISSUE THREAD

**Issue by afritzler** [squat/modulus#3]
Thanks a lot for the great project and the great talk at KubeCon Europe! :)

Am I correct, that the 2 missing pieces now are 1. Nvidia Docker runtime and 2. Kubernetes Device Plugin?

Regarding 1: Do you have some hints on how to get this up and running on CoreOS? There're a couple of projects on github covering how to get the Nvidia docker runtime up and running - I am not sure which one to use.

Regarding 2: Can I use the official off-the-shelf Nvidia Device Plugin[1]?

Regards,
Andreas

[1] https://github.com/NVIDIA/k8s-device-plugin

**Comment by squat** [comment]
Andreas, thank you for listening to the talk! The only missing piece to use this repository is a NVIDIA device plugin (and any dependencies it may have).

In my talk, and in the demo [0], I use the GPU device plugin created by Google Cloud Project. This device plugin is host-OS- and cloud-agnostic; it is not specific to Google Cloud. In fact, I am using it on a bare-metal cluster at the moment. Furthermore, this is the default device plugin for NVIDIA GPUs available in the add-on directory of the Kubernetes repo [1]. For now, I would recommend using this device plugin in favor of the one created by NVIDIA as it does not have any container runtime dependencies. That means, you _don't_ need to install the NVIDIA docker runtime to use this device plugin. Getting up and running with the GCP device plugin is as simple as:

* deploying a K8s cluster on Container Linux on your preffered cloud; and
* creating the device plugin daemonset

Please take a look at the demo code from my talk for reference [0]. If it is missing details or could be improved, please file and issue or make a PR there.

[0] https://github.com/squat/kubeconeu2018
[1] https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/device-plugins/nvidia-gpu/daemonset.yaml

**Comment by afritzler** [comment]
Thanks a lot for the quick response! I was not aware that you don't really need the NVIDIA docker runtime. This simplifies things a lot.

So to recap: 

0. create a cluster
1. deploy your modulus daemonset
2. deploy the device plugin above
3. deploy cuda based workload with the corresponding tolerations

I will give this a try.

PS. Can you elaborate a little bit more on why the GCloud device plugin doesn't rely on the NVIDIA runtime? (or point me to some docs? still pretty much a blackbox to me :-P)

**Comment by squat** [comment]
Yes, those steps are exactly right.
The NVIDIA container runtime has many potential values; one of the reasons someone may choose to use the NVIDIA runtime is to be able to transparently run containers without explicitly specifying NVIDIA devices and library bind mounts. With the NVIDIA container runtime, you can run a GPU-powered container with just:

```sh
docker run -it --entrypoint=nvidia-smi nvidia/cuda:8.0-cudnn5-devel
```

This is possible because the NVIDIA container runtime tells Docker to mount the devices and libraries on your behalf. However, this container runtime is not strictly necessary: you can run a GPU-powered container by manually specifying the NVIDIA devices and libraries [0] using vanilla docker:

```sh
docker run -it --device=/dev/nvidiactl --device=/dev/nvidia-uvm --device=/dev/nvidia0 --volume=/opt/nvidia/387.34:/usr/local/nvidia:ro --entrypoint=nvidia-smi nvidia/cuda:8.0-cudnn5-devel
```

How does this relate to the device plugins? Well, the NVIDIA device plugin leverages the NVIDIA container runtime to do the NVIDIA device and library mounting. On the other hand, the GCP device plugin does the NVIDIA device and library mounting _itself_ [1]. In this way, the GCP device plugin is analogous to the second shell snippet. This means that the GCP device plugin needs to know where your NVIDIA libraries are installed on the host OS; it has default values [2] that can be overridden [3].

The trade-off with using the GCP device plugin is:
* ease of installation +
* potentially missing out on future magic that the NVIDIA container runtime plans to provide like advanced GPU monitoring -

[0] https://github.com/squat/modulus/tree/master/nvidia#leveraging-nvidia-gpus-in-containers
[1] https://github.com/GoogleCloudPlatform/container-engine-accelerators/blob/master/pkg/gpu/nvidia/beta_plugin.go#L78-L90
[2] https://github.com/GoogleCloudPlatform/container-engine-accelerators/tree/master/cmd/nvidia_gpu#kubernetes-device-plugin-for-nvidia-gpus
[3] https://github.com/squat/kubeconeu2018/blob/master/manifests/device-plugin.yaml#L32

**Comment by squat** [comment]
Closing for now. Please re-open if there are any problems.

**Comment by afritzler** [comment]
Sorry for the late response and Wow! Thanks a lot for the detailed explanation. That really helped a lot. 

In the meantime I was able to get everything running on an AWS P2 + CoreOS based K8s cluster.

Btw. are you planning to maintain modulus in the future?

**Comment by squat** [comment]
Great! And yes, I am using this project for my own GPU clusters for ML purposes so I will maintain this at least until an official tool is released. For example, I understand the folks at NVIDIA are developing a mostly distro-agnostic tool for installing GPU drivers that will solve the current fragmentation of having OS-specific installers. In this case, modulus could be deprecated in favor of such a tool.

**Comment by afritzler** [comment]
Thanks for the update. 

Is there a way to reach out to you outside of github issues?

**Comment by squat** [comment]
@afritzler you can message me on the kubernetes slack. I am @squat 👍
